services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${INNER_POSTGRES_PORT}
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - database
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend/infrastructure/database/migrations:/app/backend/infrastructure/database/migrations
    networks:
      - dev-sync

  database:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${OUTER_POSTGRES_PORT}:${INNER_POSTGRES_PORT}"
    volumes:
      - dev_sync_pg_data:/var/lib/postgresql/data
    networks:
      - dev-sync


volumes:
  dev_sync_pg_data:
    driver: local


networks:
  dev-sync:
    driver: bridge
