[tool.ruff]
lint.select = ["E", "W", "F", "B", "N", "UP", "SIM", "PL", "PERF", "RUF"]
lint.ignore = ["PLR0913", "RUF012"]
line-length = 100
exclude = ["backend/infrastructure/database/migrations"]

[tool.ruff.lint.pydocstyle]
convention = "google"
